#!/bin/sh
mkdir -p /tmpfs
mount -o size=1G -t tmpfs tmpfs /tmpfs
echo "Unpacking from IPFS"
ipfs files read /app/bundle.tar.gz | tar -C /tmpfs -zxf - --warning=no-timestamp
echo "Starting container"
crun run -b /tmpfs app
